// Generated by https://quicktype.io

import { Computer } from "../computers/computer";

export class Maintenance {
    id:          number;
    computer:  Computer = new Computer();
    cleanType:   string;
    description: string;
    date:        Date;
}



