// Generated by https://quicktype.io

import { Laboratory } from "src/app/laboratories/laboratory";

export class Diagnostic {
    id:          number;
    laboratory:  Laboratory =new Laboratory();
    serviceTag:  string;
    description: string;
    image1:      null;
    image2:      null;
    image3:      null;
    date:        Date;
}


